language: java
jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7

#branches:
#  only:
#    - master

notifications:
  email:
    - peathal@yahoo.de

after_success:
  - cd core; mvn -Pcobertura clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:cobertura  